services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: research_radar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./fastapi-server
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/research_radar
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./react-client
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: