"""add OpenAlex IDs and model relationships

Revision ID: d9c18ea946ad
Revises: 1547dbd91dc4
Create Date: 2026-08-10 23:55:27.462450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c18ea946ad'
down_revision: Union[str, Sequence[str], None] = '1547dbd91dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('openalex_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'authors', ['openalex_id'])
    op.add_column('topics', sa.Column('openalex_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'topics', ['openalex_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_column('topics', 'openalex_id')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'openalex_id')
    # ### end Alembic commands ###
